WIP : PHP8
infinum/eightshift-boilerplate pull request #273
Opened 2023-10-26 06:53 UTC by iruzevic

# Description

- updating composer packages

2023-10-26 07:48 UTC, piqusy submitted a review, later dismissed

2023-10-26 09:59 UTC, dingo-d commented
The `npx create` command worked nicely on PHP 8.1.23 and node v20.9.0, but the header and footer menu seems to be missing an icon 

<img width="891" alt="image" src="https://github.com/infinum/eightshift-boilerplate/assets/8638515/978f858f-d021-48ed-89dd-687bcf87b5ec">

The only warning I got was when I entered the customizer screen

```php
[26-Oct-2023 09:58:44 UTC] PHP Warning:  Attempt to read property "title" on null in /Users/deniszoljom/Sites/wp-testing/wp-includes/class-wp-customize-widgets.php on line 905
[26-Oct-2023 09:58:44 UTC] PHP Stack trace:
[26-Oct-2023 09:58:44 UTC] PHP   1. {main}() /Users/deniszoljom/.composer/vendor/laravel/valet/server.php:0
[26-Oct-2023 09:58:44 UTC] PHP   2. require() /Users/deniszoljom/.composer/vendor/laravel/valet/server.php:250
[26-Oct-2023 09:58:44 UTC] PHP   3. do_action($hook_name = 'customize_controls_print_footer_scripts') /Users/deniszoljom/Sites/wp-testing/wp-admin/customize.php:302
[26-Oct-2023 09:58:44 UTC] PHP   4. WP_Hook->do_action($args = [0 => '']) /Users/deniszoljom/Sites/wp-testing/wp-includes/plugin.php:517
[26-Oct-2023 09:58:44 UTC] PHP   5. WP_Hook->apply_filters($value = '', $args = [0 => '']) /Users/deniszoljom/Sites/wp-testing/wp-includes/class-wp-hook.php:334
[26-Oct-2023 09:58:44 UTC] PHP   6. WP_Customize_Widgets->output_widget_control_templates('') /Users/deniszoljom/Sites/wp-testing/wp-includes/class-wp-hook.php:310
```
but nobody uses customizer so that's fine. 

I'll need to do a deep dive to check if everything works as intended, but so far so good 👍🏼

2023-10-27 13:15 UTC, iobrado submitted a review, later dismissed

2023-10-30 08:37 UTC, iobrado submitted a review, later dismissed

2023-10-30 08:40 UTC, goranalkovic-infinum requested changes

2023-10-30 08:40 UTC, goranalkovic-infinum commented on composer.json
> +		"php": "^7.4 || >=8.0",
```suggestion
		"php": ">=7.4",
```
we can always change it to >=7.4 <= 8.2 for example if 8.3 adds breaking changes
(copy-paste from the FE libs comment)

2023-10-30 09:09 UTC, dingo-d approved these changes

2023-10-30 13:58 UTC, goranalkovic-infinum approved these changes

2023-10-31 07:14 UTC, kancijan approved these changes

2023-11-06 09:41 UTC, merged